#!/bin/sh

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Cyan='\033[0;36m'         # Cyan
Red='\033[0;31m'          # Red
Yellow='\033[0;33m'       # Yellow
Green='\033[0;32m'        # Green


# Find csproj files in the root directory ONLY
for csproj in $(find . -maxdepth 1 -name "*.csproj"); do
    echo -e "${Cyan}Checking Format on $csproj${Color_Off}"

    dotnet format $csproj --verify-no-changes --exclude "**/Mediapipe/**"

    rc=$?

    if [[ $rc != 0 ]]; then
        echo -e "${Yellow}Code is not formatted correctly in project $csproj!${Color_Off}"
        echo -e "${Yellow}Please run 'dotnet format -v diag $csproj' --exclude \"**/Mediapipe/**\ to format your code.${Color_Off}"
        exit $rc
    else 
        echo -e "${Green}Code for $csproj is formatted correctly!${Color_Off}"
    fi
done

exit $rc
