#!/bin/sh

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Cyan='\033[0;36m'         # Cyan
Red='\033[0;31m'          # Red
Yellow='\033[0;33m'       # Yellow
Green='\033[0;32m'        # Green

csproject='NOVA.csproj'

echo -e "${Cyan}Checking Format on ${csproject}...${Color_Off}"

dotnet format $csproject --verify-no-changes

rc=$?

if [[ $rc != 0 ]]; then
        echo -e "${Yellow}Code is not formatted correctly in project ${csproject}!${Color_Off}"
        echo -e "${Yellow}Please run 'dotnet format -v diag ${csproject}' to format your code.${Color_Off}"
else 
    echo -e "${Green}Code is formatted correctly!${Color_Off}"
fi

exit $rc