name: Format Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: ['9.0.x']

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Check Code Formatting
        run: |
          dotnet restore NOVA.csproj
          dotnet format NOVA.csproj --verify-no-changes

          rc=$?

          if [[ $rc != 0 ]]; then
            echo -e "Code is not formatted correctly!"
            exit $rc
          else 
            echo -e "Code is formatted correctly!"
          fi
        shell: bash